/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TableauRouteImport } from './routes/tableau'
import { Route as RecurrentesRouteImport } from './routes/recurrentes'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PartageRouteImport } from './routes/partage'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as EpargneRouteImport } from './routes/epargne'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as AvoirRouteImport } from './routes/avoir'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MoisIndexRouteImport } from './routes/mois.index'
import { Route as MoisYearMonthRouteImport } from './routes/mois.$year.$month'

const TableauRoute = TableauRouteImport.update({
  id: '/tableau',
  path: '/tableau',
  getParentRoute: () => rootRouteImport,
} as any)
const RecurrentesRoute = RecurrentesRouteImport.update({
  id: '/recurrentes',
  path: '/recurrentes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PartageRoute = PartageRouteImport.update({
  id: '/partage',
  path: '/partage',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const EpargneRoute = EpargneRouteImport.update({
  id: '/epargne',
  path: '/epargne',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const AvoirRoute = AvoirRouteImport.update({
  id: '/avoir',
  path: '/avoir',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoisIndexRoute = MoisIndexRouteImport.update({
  id: '/mois/',
  path: '/mois/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoisYearMonthRoute = MoisYearMonthRouteImport.update({
  id: '/mois/$year/$month',
  path: '/mois/$year/$month',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/avoir': typeof AvoirRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/epargne': typeof EpargneRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/partage': typeof PartageRoute
  '/profil': typeof ProfilRoute
  '/recurrentes': typeof RecurrentesRoute
  '/tableau': typeof TableauRoute
  '/mois/': typeof MoisIndexRoute
  '/mois/$year/$month': typeof MoisYearMonthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/avoir': typeof AvoirRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/epargne': typeof EpargneRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/partage': typeof PartageRoute
  '/profil': typeof ProfilRoute
  '/recurrentes': typeof RecurrentesRoute
  '/tableau': typeof TableauRoute
  '/mois': typeof MoisIndexRoute
  '/mois/$year/$month': typeof MoisYearMonthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/avoir': typeof AvoirRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/epargne': typeof EpargneRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/partage': typeof PartageRoute
  '/profil': typeof ProfilRoute
  '/recurrentes': typeof RecurrentesRoute
  '/tableau': typeof TableauRoute
  '/mois/': typeof MoisIndexRoute
  '/mois/$year/$month': typeof MoisYearMonthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/avoir'
    | '/confidentialite'
    | '/epargne'
    | '/mentions-legales'
    | '/partage'
    | '/profil'
    | '/recurrentes'
    | '/tableau'
    | '/mois/'
    | '/mois/$year/$month'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/avoir'
    | '/confidentialite'
    | '/epargne'
    | '/mentions-legales'
    | '/partage'
    | '/profil'
    | '/recurrentes'
    | '/tableau'
    | '/mois'
    | '/mois/$year/$month'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/avoir'
    | '/confidentialite'
    | '/epargne'
    | '/mentions-legales'
    | '/partage'
    | '/profil'
    | '/recurrentes'
    | '/tableau'
    | '/mois/'
    | '/mois/$year/$month'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  AvoirRoute: typeof AvoirRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  EpargneRoute: typeof EpargneRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PartageRoute: typeof PartageRoute
  ProfilRoute: typeof ProfilRoute
  RecurrentesRoute: typeof RecurrentesRoute
  TableauRoute: typeof TableauRoute
  MoisIndexRoute: typeof MoisIndexRoute
  MoisYearMonthRoute: typeof MoisYearMonthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tableau': {
      id: '/tableau'
      path: '/tableau'
      fullPath: '/tableau'
      preLoaderRoute: typeof TableauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recurrentes': {
      id: '/recurrentes'
      path: '/recurrentes'
      fullPath: '/recurrentes'
      preLoaderRoute: typeof RecurrentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partage': {
      id: '/partage'
      path: '/partage'
      fullPath: '/partage'
      preLoaderRoute: typeof PartageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epargne': {
      id: '/epargne'
      path: '/epargne'
      fullPath: '/epargne'
      preLoaderRoute: typeof EpargneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avoir': {
      id: '/avoir'
      path: '/avoir'
      fullPath: '/avoir'
      preLoaderRoute: typeof AvoirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mois/': {
      id: '/mois/'
      path: '/mois'
      fullPath: '/mois/'
      preLoaderRoute: typeof MoisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mois/$year/$month': {
      id: '/mois/$year/$month'
      path: '/mois/$year/$month'
      fullPath: '/mois/$year/$month'
      preLoaderRoute: typeof MoisYearMonthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  AvoirRoute: AvoirRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  EpargneRoute: EpargneRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PartageRoute: PartageRoute,
  ProfilRoute: ProfilRoute,
  RecurrentesRoute: RecurrentesRoute,
  TableauRoute: TableauRoute,
  MoisIndexRoute: MoisIndexRoute,
  MoisYearMonthRoute: MoisYearMonthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
