/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EpargneRouteImport } from './routes/epargne'
import { Route as AvoirRouteImport } from './routes/avoir'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MoisIndexRouteImport } from './routes/mois.index'
import { Route as MoisYearMonthRouteImport } from './routes/mois.$year.$month'

const EpargneRoute = EpargneRouteImport.update({
  id: '/epargne',
  path: '/epargne',
  getParentRoute: () => rootRouteImport,
} as any)
const AvoirRoute = AvoirRouteImport.update({
  id: '/avoir',
  path: '/avoir',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoisIndexRoute = MoisIndexRouteImport.update({
  id: '/mois/',
  path: '/mois/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoisYearMonthRoute = MoisYearMonthRouteImport.update({
  id: '/mois/$year/$month',
  path: '/mois/$year/$month',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avoir': typeof AvoirRoute
  '/epargne': typeof EpargneRoute
  '/mois/': typeof MoisIndexRoute
  '/mois/$year/$month': typeof MoisYearMonthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avoir': typeof AvoirRoute
  '/epargne': typeof EpargneRoute
  '/mois': typeof MoisIndexRoute
  '/mois/$year/$month': typeof MoisYearMonthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avoir': typeof AvoirRoute
  '/epargne': typeof EpargneRoute
  '/mois/': typeof MoisIndexRoute
  '/mois/$year/$month': typeof MoisYearMonthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/avoir' | '/epargne' | '/mois/' | '/mois/$year/$month'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/avoir' | '/epargne' | '/mois' | '/mois/$year/$month'
  id: '__root__' | '/' | '/avoir' | '/epargne' | '/mois/' | '/mois/$year/$month'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvoirRoute: typeof AvoirRoute
  EpargneRoute: typeof EpargneRoute
  MoisIndexRoute: typeof MoisIndexRoute
  MoisYearMonthRoute: typeof MoisYearMonthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/epargne': {
      id: '/epargne'
      path: '/epargne'
      fullPath: '/epargne'
      preLoaderRoute: typeof EpargneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avoir': {
      id: '/avoir'
      path: '/avoir'
      fullPath: '/avoir'
      preLoaderRoute: typeof AvoirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mois/': {
      id: '/mois/'
      path: '/mois'
      fullPath: '/mois/'
      preLoaderRoute: typeof MoisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mois/$year/$month': {
      id: '/mois/$year/$month'
      path: '/mois/$year/$month'
      fullPath: '/mois/$year/$month'
      preLoaderRoute: typeof MoisYearMonthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvoirRoute: AvoirRoute,
  EpargneRoute: EpargneRoute,
  MoisIndexRoute: MoisIndexRoute,
  MoisYearMonthRoute: MoisYearMonthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
